### ISSUE TITLE
US-1.9 - As a Developer, I will enable the system to provide feedback from the tests to Cytoscape.

### ISSUE THREAD

**Issue by kemaric** [Swen670Grp1/cytoscape-platform-tests-js#23] opened 2018-11-14 02:08 UTC
US-1.9 - As a Developer, I will enable the system to provide feedback from the tests to Cytoscape.

**Comment by kouissar** [comment] 2018-11-15 00:41
What requirement is this?

**Comment by kouissar** [comment] 2018-11-16 03:13
this appears to be a duplicate of 1.6 req

**Closed as completed by kouissar** 2018-11-16 03:13 UTC
Labels: duplicate
